language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t deepaksivaramanpandi/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true deepaksivaramanpandi/react-test npm test -- --coverage

after_success:
    - docker build -t deepaksivaramanpandi/multi-client ./client
    - docker build -t deepaksivaramanpandi/multi-nginx ./nginx
    - docker build -t deepaksivaramanpandi/multi-server ./server
    - docker build -t deepaksivaramanpandi/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push deepaksivaramanpandi/multi-client
    - docker push deepaksivaramanpandi/multi-nginx
    - docker push deepaksivaramanpandi/multi-server
    - docker push deepaksivaramanpandi/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-571016850747
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY




